include classpath("application.conf")

node-address {
  port = 9324
}

rest-sqs {
  bind-port = 9324
}

auto-create-queues {
  enabled = false
  template {
    defaultVisibilityTimeout = 60 seconds
    tags {
        type = "dynamic"
    }
  }
}

queues {
  sim-results { }
}