AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Monolith-esque API.

Globals:
  Function:
    Environment:
      Variables:
        LOG_LEVEL: "debug"

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: Environment stage (e.g., dev, test, prod)
  ResultsQueueName:
    Type: String
    Default: sim-results

Resources:
  MonolithAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
  SimulationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: simulation-queue
      MessageRetentionPeriod: 300
      VisibilityTimeout: 30
  CreateJobFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      MemorySize: 256
      PackageType: Image
      Environment:
        Variables:
          RESULTS_QUEUE_NAME: !Ref ResultsQueueName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MonolithAPI
            Path: /simulate
            Method: post
  RunSimulationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      #MemorySize: 256
      PackageType: Image
      Events:
        SQS:
          Type: SQS
          Properties:
            Queue: !GetAtt SimulationQueue.Arn
            BatchSize: 1
    Metadata:
      DockerTag: run-sim
      DockerContext: ./backend
      Dockerfile: Dockerfile.run-sim
