ARG GOLANG_VERSION=1.26-alpine
FROM golang:${GOLANG_VERSION} AS build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 \
    GOOS=linux \
    go build \
    -tags lambda.norpc \
    -o main ./cmd/create-job/main.go

FROM alpine-latest
WORKDIR /app
COPY --from=build /app/main main
ENTRYPOINT ["./main"]