version: "3"

tasks:
  lint:
    desc: Run golangci-lint on the backend codebase
    cmds:
      - golangci-lint run
  format:
    desc: Format the backend codebase
    cmds:
      - go fmt ./...
  test:
    desc: Run the backend tests
    cmds:
      - go test ./...
  test-integration:
    desc: Run the backend integration tests
    cmds:
      - go test -tags=integration ./...