apiVersion: v1
kind: Namespace
metadata:
  name: scylla-operator
  labels:
    istio.io/dataplane-mode: ambient
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: scylla-operator
  namespace: kube-system
spec:
  chart: scylla-operator
  repo: https://scylla-operator-charts.storage.googleapis.com/stable
  targetNamespace: scylla-operator
  valuesContent: |-
    replicas: 1